Added `xcpretty` to CI log output

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,9 +29,9 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,name=Any Mac"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS" | xcpretty && exit ${PIPESTATUS[0]}
 
   macOS-12:
     name: macOS 12 Monterey
@@ -39,9 +39,9 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,name=Any Mac"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS" | xcpretty && exit ${PIPESTATUS[0]}
 
   macCatalyst:
     name: macCatalyst
@@ -49,9 +49,9 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS,variant=Mac Catalyst"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=macOS,variant=Mac Catalyst" | xcpretty && exit ${PIPESTATUS[0]}
 
   iOS:
     name: iOS
@@ -59,9 +59,9 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: iPhone 12 Simulator - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: iPhone 12 Simulator - Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=iOS Simulator,name=iPhone 12"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=iOS Simulator,name=iPhone 15" | xcpretty && exit ${PIPESTATUS[0]}
 
   tvOS:
     name: tvOS
@@ -69,19 +69,21 @@ jobs:
     steps:
     - uses: actions/checkout@main
     - name: Apple TV - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Apple TV - Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation)"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation)" | xcpretty && exit ${PIPESTATUS[0]}
 
+  # NOTES: Xcode 15 seems to have a transient bug where compiling for watchOS Simulator fails, so we have to compile for watchOS Device instead.
+  # Old destination that used to work prior to Xcode 15: "generic/platform=watchOS Simulator,name=Any watchOS Device"
   watchOS:
     name: watchOS
     runs-on: macos-latest # this must be macos, GitHub does not offer watchOS directly but we can use xcodebuild
     steps:
     - uses: actions/checkout@main
     - name: Apple Watch - Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=watchOS Simulator,name=Any watchOS Device"
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "generic/platform=watchOS Simulator,name=Any watchOS Device" | xcpretty && exit ${PIPESTATUS[0]}
     - name: Apple Watch - Unit Tests
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)"
+      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftRadix-CI" -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" | xcpretty && exit ${PIPESTATUS[0]}
 
 
 # xcodebuild test reference:
